name: ria_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.2

  # ------------- Packages -------------- #
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  get_storage: ^2.1.1
  http: ^1.2.2
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  iconsax: ^0.0.8
  get: ^4.6.6
  flutter_blue_plus: ^1.32.12
  google_fonts: ^6.2.1
  syncfusion_flutter_charts: ^26.2.14
  fl_chart: ^0.69.0
  shared_preferences: ^2.3.2

  # ------------- Packages End ------------ #

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # ------------ Local Assets ------------- #
  assets:
    - assets/images/logos/

  # ----------- Local Fonts --------------- #
  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceCodePro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceCodePro-Italic.ttf
          style: italic
        - asset: assets/fonts/SourceCodePro-Medium.ttf
          weight: 500
        - asset: assets/fonts/SourceCodePro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\SourceCodePro-Bold.ttf
          weight: 800
